{
 "title": "Agones Controller go-client workqueue",
 "tags": [
  "agones",
  "client-go",
  "controller"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "workqueue",
    "label": "workqueue",
    "query": "label_values(agones_k8s_client_workqueue_items_total,queue_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workqueue depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clamp_min(agones_k8s_client_workqueue_depth{queue_name=~\"$workqueue\"},0)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Workqueue items rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(agones_k8s_client_workqueue_items_total{queue_name=~\"$workqueue\"}[1m])",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Workqueue retry items rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(agones_k8s_client_workqueue_retries_total{queue_name=~\"$workqueue\"}[1m])",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Workqueue average items duration",
   "type": "graph",
   "description": "How long an item stays in the work queue.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_workqueue_latency_seconds_sum{queue_name=~\"$workqueue\"}[1m]) / rate(agones_k8s_client_workqueue_latency_seconds_count{queue_name=~\"$workqueue\"}[1m])) by(queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Workqueue average work duration",
   "type": "graph",
   "description": "How long processing an item from the work queue takes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_workqueue_work_duration_seconds_sum{queue_name=~\"$workqueue\"}[1m]) / rate(agones_k8s_client_workqueue_work_duration_seconds_count{queue_name=~\"$workqueue\"}[1m])) by(queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  }
 ]
}