{
 "title": "Agones Status",
 "description": "Agones CRD controller status",
 "tags": [
  "agones",
  "controller"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "healthcheck",
    "query": "label_values(agones_healthcheck_status, check)\t"
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "(process_start_time_seconds{app=\"agones\",agones_dev_role=\"controller\"}) * 1000"
    }
   ]
  },
  {
   "title": "Controller",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{app=\"agones\",kubernetes_pod_name=~\"agones-controller.*\"} OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Allocators Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((process_start_time_seconds{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}) * 1000)"
    }
   ]
  },
  {
   "title": "Allocators Live Pod",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Allocators Total Pods",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{app=\"agones\",kubernetes_pod_name=~\"agones-allocator.*\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "repeat": "healthcheck",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "health check - $healthcheck",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(agones_healthcheck_status{check=\"$healthcheck\"}) OR on() vector(1)",
     "legendFormat": "{{check}}"
    }
   ]
  }
 ]
}