apiVersion: v1
kind: Secret

metadata:
  name: {{name}}-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: "git"
  url: "git@github.com:emortalmc/{{name}}.git"
