apiVersion: v1
kind: Secret

metadata:
  name: tower-defence-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: "git"
  url: "git@github.com:ZakShearman/mc-tower-defence.git"

