{
 "title": "MC / Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "fleet",
    "query": {
     "query": "label_values(minestom_players, fleet)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(minestom_players{fleet=\"$fleet\"}, server)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "show_req_lims", "query": "false : 0, true : 1 " }
  ]
 },
 "panels": [
  {
   "title": "MC Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(minestom_packets_total{pod=\"$pod_name\"}[$interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "MC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "MC Server Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_players{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Chunks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_chunks{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "MC Server Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_entities{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_instances{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Java Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod_name\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Java Off-Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=\"$pod_name\", area=\"nonheap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "k8s CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=\"$pod_name\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=\"$pod_name\", resource=\"cpu\"}\n) / $show_req_lims\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=\"$pod_name\", resource=\"cpu\"}\n) / $show_req_lims\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{pod=\"$pod_name\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}