apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: emortalmc

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-access
  namespace: emortalmc

subjects:
  - kind: ServiceAccount
    name: friend-manager
  - kind: ServiceAccount
    name: private-message
  - kind: ServiceAccount
    name: player-transporter
  - kind: ServiceAccount
    name: gameserver
  - kind: ServiceAccount
    name: matchmaker

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader