apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: additional-agones-sdk-access
  namespace: emortalmc

subjects:
  - kind: ServiceAccount
    name: default-gameserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk