loki:
  serviceName: loki

config:
  snippets:
    pipelineStages:
      - cri: {}
      - multiline:
          firstline: '^\[\d{2}:\d{2}:?\d{2}\s\S+\]:? \[.*]'
          max_wait_time: 3s
          max_lines: 128
      - pack: {}
