loki:
  commonConfig:
    replication_factor: 1

  storage:
    type: 'filesystem'

  auth_enabled: false

  monitoring:
    selfMonitoring:
      grafanaAgent:
        installOperator: false

singleBinary:
  replicas: 1
  persistence:
    size: 20Gi
