apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-player
  namespace: emortalmc
  labels:
    app: mc-player

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-player

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: mc-player
    spec:
      containers:
        - name: mc-player
          image: ghcr.io/emortalmc/mc-player-service:cef5a501764c0cd9b3ead9a53f5f3d72206e4cb4
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
