apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: badge-manager

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: mc-player
---
apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: mc-player

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: mc-player
