apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"

data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Pyroscope
        type: pyroscope-datasource
        access: proxy
        jsonData:
          path: http://pyroscope-io.pyroscope.svc:4040
          
        version: 1
        editable: false