apiVersion: v1
kind: ConfigMap

metadata:
  name: pyroscope-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"

data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: "Pyroscope"
        type: grafana-pyroscope-datasource
        access: proxy
        url: http://pyroscope-query-frontend.monitoring.svc.cluster.local:4040
        version: 1
