# These values are modified from the values-micro-services.yaml file.
# We don't need to run pyroscope with such high resources, so we can reduce the memory and cpu requests.

pyroscope:
  extraArgs:
    store-gateway.sharding-ring.replication-factor: "1"
  components:
    querier:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 1
    query-frontend:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 100m
    query-scheduler:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 100m
    distributor:
      kind: Deployment
      replicaCount: 2
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 500m
    ingester:
      kind: StatefulSet
      replicaCount: 1
      terminationGracePeriodSeconds: 600
      resources:
        limits:
          memory: 6Gi
        requests:
          memory: 2Gi
          cpu: 1
    compactor:
      kind: StatefulSet
      replicaCount: 1
      persistence:
        enabled: false
      resources:
        limits:
          memory: 8Gi
        requests:
          memory: 4Gi
          cpu: 1
    store-gateway:
      kind: StatefulSet
      replicaCount: 1
      persistence:
        # The store-gateway needs not need persistent storage, but we still run it as a StatefulSet
        # This is to avoid having blocks of data being
        enabled: false
      resources:
        limits:
          memory: 8Gi
        requests:
          memory: 4Gi
          cpu: 1
      readinessProbe:
        # The store gateway can be configured to wait on startup for ring stability to be reached before it becomes
        # ready. See the `store-gateway.sharding-ring.wait-stability-min-duration` server argument for more information.
        #
        # Depending on this flag and the number of tenants + blocks that need to be synced on startup, pods can take
        # some time to become ready. This value can be used to ensure Kubernetes waits long enough and reduce errors.
        initialDelaySeconds: 60
    tenant-settings:
      kind: Deployment
      replicaCount: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 256Mi
          cpu: 1

minio:
  enabled: true
  persistence:
    size: 20Gi
