apiVersion: v1
kind: ServiceAccount

metadata:
  name: default-gameserver
  namespace: emortalmc

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: matchmaker
  namespace: emortalmc

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: mongodb-database
  namespace: emortalmc
