{
 "title": "Agones Autoscalers",
 "tags": [
  "agones",
  "autoscaler"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name",
    "query": {
     "query": "label_values(agones_fleet_autoscalers_desired_replicas_count,name)"
    }
   },
   { "name": "namespace", "label": "namespace", "query": "agones-system" }
  ]
 },
 "panels": [
  {
   "title": "Fleet % Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(label_replace(agones_fleets_replicas_count{type=\"allocated\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"}))\n\n/ on(name)\n\n(label_replace(agones_fleets_replicas_count{type=\"desired\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\",namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Fleet % Ready",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(label_replace(agones_fleets_replicas_count{type=\"ready\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"}))\n\n/ on(name)\n\n(label_replace(agones_fleets_replicas_count{type=\"desired\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Current Desired Scaling Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\", namespace=\"$namespace\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Autoscaler Current Desired Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_desired_replicas_count{name=\"$name\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Buffer Size Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_size{name=\"$name\",type=\"count\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Min buffer size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_limits{name=\"$name\",type=\"min\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Current Desired Scaling %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\", namespace=\"$namespace\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"})\n\n  / \n\nagones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"} "
    }
   ]
  },
  {
   "title": "Autoscaler Current Replica Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Buffer Size %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_size{name=\"$name\",type=\"percentage\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Max buffer size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_buffer_limits{name=\"$name\",type=\"max\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Fleet Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"}",
     "legendFormat": "fas current replicas"
    },
    {
     "expr": "agones_fleet_autoscalers_desired_replicas_count{name=\"$name\", namespace=\"$namespace\"}",
     "legendFormat": "fas desired replicate"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"allocated\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"})",
     "legendFormat": "fleet allocated"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"ready\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"})",
     "legendFormat": "fleet ready"
    },
    {
     "expr": "label_replace(agones_fleets_replicas_count{type=\"desired\", namespace=\"$namespace\"},\"fleet_name\",\"$1\",\"name\",\"(.*)\")  * on (fleet_name) group_left()  (agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"})",
     "legendFormat": "fleet desired"
    },
    {
     "expr": "(agones_fleet_autoscalers_desired_replicas_count{name=\"$name\", namespace=\"$namespace\"} - agones_fleet_autoscalers_current_replicas_count{name=\"$name\", namespace=\"$namespace\"})",
     "legendFormat": "desired scaling"
    }
   ]
  },
  {
   "title": "Scaling Limited",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_limited{name=\"$name\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Able to scale",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "agones_fleet_autoscalers_able_to_scale{name=\"$name\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}