{
 "title": "Agones Controller go-client requests",
 "tags": [
  "agones",
  "controller",
  "client-go"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests rate by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(agones_k8s_client_http_request_total[5m])",
     "legendFormat": "{{status_code}} {{verb}}"
    }
   ]
  },
  {
   "title": "Requests rate by verb and path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_http_request_duration_seconds_count[5m])) by (endpoint,verb)",
     "legendFormat": "{{verb}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(agones_k8s_client_http_request_duration_seconds_sum[5m]) / rate(agones_k8s_client_http_request_duration_seconds_count[5m])) by (endpoint,verb)",
     "legendFormat": "{{verb}} {{endpoint}}"
    }
   ]
  }
 ]
}