apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: argocd-ingress
  namespace: argocd

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`argo.{{host}}`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: kani-argo-middleware

---
apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: kani-argo-middleware
  namespace: argocd

spec:
  forwardAuth:
    # Replace <AUD> with your Cloudflare Access application audience.
    # address: http://<service-name>.<namespace>.svc.cluster.local/<aud>
    address: http://kani.traefik.svc.cluster.local/{{audience}}

    # Optionally you can forward the authenticated user's email (or common name) to the backend.
    authResponseHeaders:
      - "X-Auth-User"
