apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: grafana-ingress
  namespace: monitoring

spec:
  entryPoints:
    - websecure

  routes:
    - kind: Rule
      match: Host(`metrics.{{host}}`)
      services:
        - name: prom-stack-grafana
          port: 80
      middlewares:
        - name: kani-grafana-middleware

---
apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: kani-grafana-middleware
  namespace: monitoring

spec:
  forwardAuth:
    # Replace <AUD> with your Cloudflare Access application audience.
    # address: http://<service-name>.<namespace>.svc.cluster.local/<aud>
    address: http://kani.traefik.svc.cluster.local/{{aud}}

    # Optionally you can forward the authenticated user's email (or common name) to the backend.
    authResponseHeaders:
      - "X-Auth-User"
