apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: linkerd-ingress
  namespace: linkerd

spec:
  entryPoints:
    - web

  routes:
    - kind: Rule
      match: Host(`linkerd.{{host}}`)
      services:
        - name: web
          port: 8084
      middlewares:
        - name: l5d-header

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware

metadata:
  name: l5d-header
  namespace: linkerd

spec:
  headers:
    customRequestHeaders:
      Host: "web.linkerd.svc.cluster.local:8084"
      Origin: ""
