apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: reposilite-ingress
  namespace: reposilite

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`repo.{{host}}`) # Replace the domain you wish to use.
      kind: Rule
      services:
        - name: reposilite
          port: http
