apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: traefik-dashboard
  namespace: traefik

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`traefik.{{host}}`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: kani-traefik-middleware

---
apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: kani-traefik-middleware
  namespace: traefik

spec:
  forwardAuth:
    # Replace <AUD> with your Cloudflare Access application audience.
    # address: http://<service-name>.<namespace>.svc.cluster.local/<aud>
    address: http://kani.traefik.svc.cluster.local/{{audience}}

    # Optionally you can forward the authenticated user's email (or common name) to the backend.
    authResponseHeaders:
      - "X-Auth-User"
