apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: emortalmc
  namespace: argocd

spec:
  description: "All the games and services that make up EmortalMC"
  sourceNamespaces: ["emortalmc"]
  sourceRepos: ["git@github.com:emortalmc/argocd-deployments.git"]
  destinations:
    - name: "Kubernetes"
      namespace: "emortalmc"
      server: "https://kubernetes.default.svc"
