apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: emortalmc
  namespace: argocd

spec:
  description: "All the games and services that make up EmortalMC"
  sourceNamespaces: ["emortalmc"]
  sourceRepos: ["git@github.com:emortalmc/*", "https://github.com/ZakShearman/mc-tower-defence.git"]
  destinations:
    - name: "Production"
      namespace: "emortalmc"
      server: "https://kubernetes.default.svc"
