{
 "title": "MC / Server",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(minestom_players, service)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(minestom_players{service=\"$service\"}, server)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "MC Server Players",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_players{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Entities",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_entities{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Tick Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(minestom_tick_time_seconds_bucket{pod=\"$pod_name\"}[$interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "MC Server Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_instances{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MC Server Entities",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minestom_chunks{pod=\"$pod_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}