apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: config-map-reader
  namespace: emortalmc

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: config-map-reader-access
  namespace: emortalmc

subjects:
  - kind: ServiceAccount
    name: default-gameserver
  - kind: ServiceAccount
    name: emortalbot

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-map-reader
