apiVersion: apps/v1
kind: Deployment
metadata:
  name: kani
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kani
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kani
    spec:
      containers:
        - name: kani
          image: joshuasing/kani:1.2.8
          imagePullPolicy: IfNotPresent

          # Environment variables
          env:
            - name: CLOUDFLARE_DOMAIN
              value: "https://emortalmc.cloudflareaccess.com"

          # Ports
          ports:
            - name: kani-http
              containerPort: 3000

          # Probes
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          resources:
            limits:
              memory: "16Mi"
              cpu: "0.10"

---
apiVersion: v1
kind: Service
metadata:
  name: kani
  namespace: traefik
  labels:
    app.kubernetes.io/name: kani
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: kani-http
  selector:
    app.kubernetes.io/name: kani