apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tower-defence
  namespace: argocd

spec:
  project: "emortalmc"
  source:
    repoURL: "https://github.com/ZakShearman/mc-tower-defence.git"
    targetRevision: "deployment"
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "emortalmc"
  syncPolicy:
    automated: {}
