apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
  namespace: emortalmc
  labels:
    app: matchmaker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: matchmaker
    spec:
      containers:
        - name: matchmaker
          image: ghcr.io/emortalmc/kurushimi:dev-1.0.10
          ports:
            - containerPort: 9090
          imagePullPolicy: Always

          env:
            - name: TRACKER_ENABLED
              value: "true"
            - name: KURUSHIMI_REDIS_HOST # Well this is horrible but Viper says we have to use a `.` to separate nested keys
              value: "redis-master"
            - name: KURUSHIMI_NAMESPACE
              value: "emortalmc"
            - name: KURUSHIMI_RABBITMQ_HOST
              value: "rabbitmq"
            - name: KURUSHIMI_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
                  optional: false
            - name: KURUSHIMI_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
                  optional: false


      serviceAccountName: matchmaker
      automountServiceAccountToken: true
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: matchmaker

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: matchmaker
