apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-player
  namespace: emortalmc
  labels:
    app: mc-player

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-player

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: mc-player
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/towerdefence-cc/mc-player-service:d8ddadbbd009a008df574b19b85c4c4763e39cf1
          ports:
            - containerPort: 9090

          env:
            - name: "SPRING_DATA_MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: mc-player

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: mc-player
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: mc-player-security

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: mc-player
