apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-player
  namespace: emortalmc
  labels:
    app: mc-player

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-player

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: mc-player
    spec:
      containers:
        - name: mc-player
          image: ghcr.io/emortalmc/mc-player-service:8eeea715eddf0b3b249ed4d407328c79c0989a09
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host
                  optional: false
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
                  optional: false
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
                  optional: false
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: mc-player

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: mc-player
