apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-manager
  namespace: emortalmc
  labels:
    app: party-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-manager

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: party-manager
    spec:
      containers:
        - name: party-manager
          image: ghcr.io/emortalmc/party-manager:320bea513b28ef31bf4575d48d70b53286e903be
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host
                  optional: false
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
                  optional: false
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
                  optional: false
            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: party-manager

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: party-manager
