apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  namespace: emortalmc
  labels:
    app: permission

spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: permission
    spec:
      containers:
        - name: permission
          image: ghcr.io/emortalmc/permission-service-go:dev-1
          ports:
            - containerPort: 9090

          env:
            - name: "MONGO_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: permission

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: permission

