apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-transporter
  namespace: emortalmc
  labels:
    app: player-transporter

spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-transporter

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: player-transporter
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/towerdefence-cc/player-transporter:8e49d000ac188616124a9e814fe9e62ae067738e
          ports:
            - containerPort: 9090

          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "production"
            - name: "SPRING_DATA_MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard

      serviceAccountName: player-transporter
      automountServiceAccountToken: true
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: player-transporter

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090

  selector:
    app: player-transporter

