apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-tracker
  namespace: emortalmc
  labels:
    app: player-tracker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-tracker

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: player-tracker
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/emortalmc/player-tracker:bb083605a0bd3dccd1f09abe0af63a79ff958c31
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: player-tracker

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: player-tracker
