apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-tracker
  namespace: emortalmc
  labels:
    app: player-tracker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-tracker

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: player-tracker
    spec:
      containers:
        - name: player-tracker
          image: ghcr.io/emortalmc/player-tracker:66a9186a7ace646413cf89b326a0661d1d3bc3ed
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host
                  optional: false
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: username
                  optional: false
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
                  optional: false
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: player-tracker

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: player-tracker
