apiVersion: apps/v1
kind: Deployment
metadata:
  name: relationship-manager
  namespace: emortalmc
  labels:
    app: relationship-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: relationship-manager

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: relationship-manager
    spec:
      containers:
        - name: relationship-manager
          image: ghcr.io/emortalmc/relationship-manager-service:dev-3
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"

            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: PLAYERTRACKERSERVICE_HOST
              value: "player-tracker"
            - name: PLAYERTRACKERSERVICE_PORT
              value: "9010"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-connection-string
                  key: connectionString.standard
            - name: PORT
              value: "9010"
---

apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: relationship-manager

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: relationship-manager
