apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: lobby
  namespace: emortalmc

spec:
  scheduling: Distributed

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%

  # TODO: Note: AllocationOverflow is not support as of Agones 1.31.0. It should be supported soon.
  # There is already support in the matchmaker for it though :O
  allocationOverflow:
    labels:
      emortal.dev/outdated: "true"

  template:
    spec:
      players:
        initialCapacity: 50
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 25565
          protocol: TCP

      health:
        initialDelaySeconds: 5
        periodSeconds: 15
        failureThreshold: 2

      template:
        metadata:
          labels:
            emortal.dev/gs-type: lobby
            emortal.dev/mc-metrics-enabled: "true"
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true

          containers:
            - name: lobby
              image: ghcr.io/emortalmc/lobby:dev-49
              command: [ "/bin/sh", "-c", "java -Xms768M -Xmx768M -jar /app/lobby.jar" ]

              resources:
                requests:
                  cpu: 502m
                  memory: 1536Mi
                limits:
                  cpu: 502m
                  memory: 1536Mi

              ports:
                - containerPort: 8081
                  name: metrics
                  protocol: TCP

              env:
                - name: minestom.velocity-forwarding-secret
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: FLEET_NAME
                  value: lobby
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: lobby
  namespace: emortalmc

spec:
  fleetName: lobby
  policy:
    type: Buffer
    buffer:
      minReplicas: 2
      bufferSize: 2
      maxReplicas: 15
