apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: lobby
  namespace: emortalmc

spec:
  scheduling: Distributed

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%

  # TODO: Note: AllocationOverflow is not support as of Agones 1.31.0. It should be supported soon.
  # There is already support in the matchmaker for it though :O
  allocationOverflow:
    labels:
      emortal.dev/outdated: "true"

  template:
    spec:
      players:
        initialCapacity: 30
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 25565
          protocol: TCP

      health:
        initialDelaySeconds: 5
        periodSeconds: 15
        failureThreshold: 2

      template:
        metadata:
          labels:
            emortal.dev/gs-type: lobby
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true

          containers:
            - name: lobby
              image: ghcr.io/emortalmc/lobby:dev-33
              command: [ "/bin/sh", "-c", "java -Xms512M -Xmx512M -jar /app/lobby.jar" ]

              resources:
                requests:
                  cpu: 502m
                  memory: 896Mi
                limits:
                  cpu: 502m
                  memory: 896Mi

              ports:
                - containerPort: 9090
                  name: metrics
                  protocol: TCP

              env:
                - name: minestom.velocity-forwarding-secret
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: lobby
  namespace: emortalmc

spec:
  fleetName: lobby
  policy:
    type: Buffer
    buffer:
      minReplicas: 2
      bufferSize: 1
      maxReplicas: 50
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gs-lobby
  namespace: emortalmc
spec:
  selector:
    matchLabels:
      emortal.dev/gs-type: "lobby"
  podMetricsEndpoints:
    - port: metrics
      path: /metrics