apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: mc-metrics-monitor
  namespace: emortalmc

spec:
  selector:
    matchLabels:
      emortal.dev/mc-metrics-enabled: "true"
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
