apiVersion: agones.dev/v1
kind: Fleet

metadata:
  name: towerdefence
  namespace: emortalmc

spec:
  replicas: 2
  scheduling: Distributed


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 25565
          protocol: TCP

      health:
        initialDelaySeconds: 5
        periodSeconds: 15
        failureThreshold: 2

      template:
        metadata:
          labels:
            emortal.dev/mc-metrics-enabled: "true"
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true

          containers:
            - name: towerdefence
              image: ghcr.io/emortalmc/towerdefence:dev-17
              command: [ "/bin/sh", "-c", "java -XX:+UseZGC -Xms192M -Xmx192M -jar /app/tower_defence.jar" ]

              resources:
                requests:
                  cpu: 300m
                  memory: 384Mi
                limits:
                  cpu: "1"
                  memory: 384Mi

              ports:
                - containerPort: 8081
                  name: metrics
                  protocol: TCP

              env:
                - name: minestom.velocity-forwarding-secret
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: FLEET_NAME
                  value: towerdefence
---
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: towerdefence
  namespace: emortalmc

spec:
  fleetName: towerdefence
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 2
      maxReplicas: 10