apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: party-manager
  namespace: emortalmc
  labels:
    strimzi.io/cluster: default

spec:
  topicName: party-manager
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour
