apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: matchmaker
  namespace: emortalmc
  labels:
    strimzi.io/cluster: default

spec:
  topicName: matchmaker
  partitions: 1
  replicas: 1
  config:
    retention.ms: 3600000 # 1 hour