apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic

metadata:
  name: mc-messages
  namespace: emortalmc
  labels:
    strimzi.io/cluster: default

spec:
  topicName: mc-messages
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 # 24 hours
