encrypt:
	sops --encrypt --age age1y87afu9m5j3p6f5adjarr5a64nzma09y353s5s3p00lla4gj69ssn8nyaw files/secrets.yaml > files/secrets.enc.yaml

decrypt:
	sops -d files/secrets.enc.yaml > files/secrets.yaml